% case_test pose
% vehicle_TPBV_ = ...
%                 struct('x0',-20,'y0',-5,'theta0',pi,...
%                 'xtf',0,'ytf',20,'thetatf',pi/2);%****perfect_case:(-20,-5,pi,0，20，pi/2)*******

%case1 pose
% vehicle_TPBV_ = ...
%                 struct('x0',7,'y0',-20,'theta0',pi,...
%                 'xtf',20,'ytf',0,'thetatf',pi/2);

%case3 pose(broad)
vehicle_TPBV_ = ...
                struct('x0',-20,'y0',-5,'theta0',0,...
                'xtf',0,'ytf',20,'thetatf',pi/2);%****perfect_case:(-20,-5,pi,0，20，pi/2)*******

% case4 pose
% vehicle_TPBV_ = ...
%                 struct('x0',-10,'y0',-20,'theta0',0,...
%                 'xtf',6,'ytf',20,'thetatf',pi/4);%****perfect_case:(-10,-20,pi,5,15,0)；(-13,0,pi;6,20,0)*****
            %feasible:(-10,-20,0;6,20,pi/4) 

% vehicle_TPBV_ = ...
%                 struct('x0',5,'y0',-20,'theta0',pi/2,...
%                 'xtf',5,'ytf',15,'thetatf',pi);

% case5 pose
% vehicle_TPBV_ = ...
%                 struct('x0',-20,'y0',-5,'theta0',pi,...
%                 'xtf',0,'ytf',20,'thetatf',pi/2);%perfect_case

save('pose.mat','vehicle_TPBV_');